# -*- coding: utf-8 -*-
"""230421

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkwGZTNP4dQ5ZGhuR1_inTqK59IazVHl
"""

def greeting():
  print('こんにちは　今日は暑いですね')

greeting()

def greeting2(name):
  print('こんにちは'+ name + 'さん、')
  print('今日は暑いですね')
greeting2('吉田')

def pie_area(radius):
  return radius*radius*3.14
pie_area(3)

def pie_area(radius):
  return radius*radius*3.14
area = pie_area(3)

def rectang_area(height,weight):
  return height*weight
rectangle = rectang_area(4,5)

print(area+rectangle)

data={'name':'山本','bill':40000,'crg':True}
print(data['name'],data['bill'])

data1={'name':'山本','bill':40000,'crg':True}
data2={'name':'吉田','bill':50000,'crg':False}
data_list=[data1,data2]
print(data_list[0]['bill'])
print(data_list[1]['crg'])

# datetime：日付を司るライブラリ
from datetime import date,timedelta
start=date(2023,4,21)
for d in range(14):
  cur = start+timedelta(days=d)
  print(cur)