# -*- coding: utf-8 -*-
"""230415

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_2HAv4UEGy62Xtqyr0Ajslgt7mCqE_C
"""

wdays=["月","火","水","木","金"]
print(wdays[1])
wdays[3] = "本"
print(wdays[3])

for i in wdays:
  print(i + "曜日")

print(wdays[1:4])

hello="こんにちは"
for i in range(100):
    print(hello)

hello="こんにちは"
for i in range(0,100):
    print(str(i+1) + "回目の" + str(hello))
    # 複数のデータ型を共存できない

for a in range(0,9):
  for b in range(0,9):
    print(str(a+1)+"×"+str(b+1)+"="+str((a+1)*(b+1)))

shikin=50000
while shikin>=0:
  print(shikin)
  shikin=shikin-5080

#A~Eのチームの総当たり対戦表を表示する
#AvsB,AvsC

teams０１=["A","B","C","D","E"]
teams０２=["A","B","C","D","E"]
for a in teams０１:
  teams02.remove(a)
  for b in teams０２:
    print(str(a)+"vs"+str(b))