# -*- coding: utf-8 -*-
"""230428

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irKGHv202vo3uFmmy6ehC2QbyWujEhoF
"""

# datetime：日付を司るライブラリ
from datetime import date,timedelta
start=date(2023,4,21)
weeks=["月","火","水","木","金","土","日"]
for d in range(14):
  cur = start+timedelta(days=d)
  wd=cur.weekday()
  # for w in weeks:
  print(cur,weeks[wd])

rfile=open('customer_master.csv', encoding='utf-8')
text=rfile.read()
rfile.close()
print(text)

"""ファイルの開封　文字列の置換"""

rfile=open('customer_master.csv', encoding='utf-8')
text=rfile.read()
rfile.close()
text=text.replace('M','男性')
print(text)

rfile=open('customer_master.csv', encoding='utf-8')
text=rfile.read()
rfile.close()
text=text.replace('F','女性')
print(text)

"""ファイル（output:txt'）の生成"""

rfile=open('customer_master.csv', encoding='utf-8')
text=rfile.read()
rfile.close()
text=text.replace('M','男性')
print(text)
wfile=open('output:txt',mode='w',encoding='utf-8')
wfile.write(text)
wfile.close()

from pathlib import Path
path=Path('sample_data')

for filepath in path.glob('california*'):
  print(filepath)

from pathlib import Path
path=Path('sample_data')

for filepath in path.glob('california*'):
  rfile=open(filepath, encoding='utf-8')
  text=rfile.read()
  rfile.close()
  text=text.replace('0000','')
  print(text)

