# -*- coding: utf-8 -*-
"""統計的検定.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CXFBQTqtv7TYgfjHkwhN9RIUmMNt76L7
"""

# Commented out IPython magic to ensure Python compatibility.
# 数値計算に使うライブラリ
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats

# グラフを描画するライブラリ
from matplotlib import pyplot as plt
import seaborn as sns
sns.set()

# 表示桁数の指定
# %precision 3
# グラフをjupyter Notebook内に表示させるための指定
# %matplotlib inline

alpha=0.05
sigma=8
n=100
df=n-1
X=150
x=148
se=sigma/np.sqrt(n)
interval=stats.t.interval(
    alpha=1-alpha,df=df,loc=X,scale=se
)
print("棄却域："+str(interval))
if x<interval[0] or x>interval[1]:
  print("帰無仮説は棄却され、対立仮説が採択される")
else:
  print("帰無仮説は受容され、対立仮説が採択されない")

alpha=0.05
sigma=8
n=100
df=n-1
X=150
x=148
se=sigma/np.sqrt(n)
interval=stats.t.interval(
    alpha=1-alpha*2,df=df,loc=X,scale=se
)
print("棄却域："+str(interval[1]))
if x>interval[1]:
  print("帰無仮説は棄却され、対立仮説が採択される")
else:
  print("帰無仮説は受容され、対立仮説が採択されない")

alpha=0.05
sigma=8
n=100
df=n-1
X=150
x=148
se=sigma/np.sqrt(n)
interval=stats.t.interval(
    alpha=1-alpha*2,df=df,loc=X,scale=se
)
print("棄却域："+str(interval[0]))
if x<interval[0]:
  print("帰無仮説は棄却され、対立仮説が採択される")
else:
  print("帰無仮説は受容され、対立仮説が採択されない")

alpha=0.05
sigma=8
n=100
df=n-1
X=150
x=148
se=sigma/np.sqrt(n)
interval=stats.t.interval(
    alpha=1-alpha,df=df,loc=X,scale=se
)
print("棄却域："+str(interval))
if x<interval[0] or x>interval[1]:
  print("帰無仮説は棄却され、対立仮説が採択される")
else:
  print("帰無仮説は受容され、対立仮説が採択されない")

health=pd.read_excel("health.xlsx")
health.head()

"""標本数"""

n=len(health["拡張期血圧"])
n

"""不偏標準偏差"""

sigma=np.std(health["拡張期血圧"],ddof=1)
sigma

"""標本平均"""

x=np.mean(health["拡張期血圧"])
x

"""標準誤差"""

# se=sigma/np.sqrt(len(health["拡張期血圧"]))
# se

alpha=0.05
df=n-1
X=60
se=sigma/np.sqrt(n)
interval=stats.t.interval(
    alpha=1-alpha,df=df,loc=X,scale=se
)
print("棄却域："+str(interval))
if x<interval[0] or x>interval[1]:
  print("帰無仮説は棄却され、対立仮説が採択される")
else:
  print("帰無仮説は受容され、対立仮説が採択されない")

